# Generated by Django 2.2.4 on 2019-09-03 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tweets',
            field=models.FileField(default=django.utils.timezone.now, upload_to='tweets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='word_cloud',
            field=models.ImageField(upload_to='image'),
        ),
    ]
