# Generated by Django 2.2.4 on 2019-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='word_cloud',
            field=models.ImageField(upload_to='image'),
        ),
    ]
